version: "3.8"

services: 
    app:
        build: .
        container_name: cmd_voice
        command: quasar dev &
        ports:
            - "3000:3000"
        volumes: 
            - .:/usr/app  
                
              
